name: Update README with Recent Activity
on:
  schedule:
    - cron: '*/30 * * * *' # Roda a cada 30 minutos
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://github.com/Vytruve.atom"
          max_post_count: 5
          readme_path: './README.md'
          template: |
            $newline - $randomEmoji(💯,🔥,💫,🚀,💡) [$title]($url)
          date_format: "dd/mm/yyyy"
          commit_message: "chore: update recent activity"
